FROM alpine:latest
MAINTAINER Julien MANTEAU
LABEL Name=evpnlab-net Version=1.0.0
RUN apk update
RUN apk add sudo bash
RUN apk add tini
RUN apk add nmap tshark tcpdump mtr iperf iperf3 htop bind-tools fping curl  
RUN apk add frr frr-pythontools
RUN apk add openssh
RUN rm -f /var/cache/apk/*
COPY .bashrc /root/.bashrc
COPY .inputrc /root/.inputrc
RUN touch /etc/frr/vtysh.conf
RUN sed -i s/bgpd=no/bgpd=yes/g /etc/frr/daemons
COPY docker-start /usr/lib/frr/docker-start
RUN chmod +x /usr/lib/frr/docker-start
ENTRYPOINT [ "/sbin/tini", "--", "/usr/lib/frr/docker-start" ]
