FROM debian:stable
MAINTAINER Julien MANTEAU
LABEL Name=evpnlab-net Version=1.0.0

ARG DEBIAN_FRONTEND=noninteractive
ARG APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=DontWarn


RUN apt-get update -o Acquire::Max-FutureTime=86400 


RUN apt-get install -y --no-install-recommends nmap tshark tcpdump mtr iperf iperf3 htop dnsutils fping curl vim 
RUN apt-get install -y --no-install-recommends bridge-utils iproute2 ifupdown vlan

RUN apt-get install -y --no-install-recommends openssh-server

COPY .inputrc /root/.inputrc

RUN apt-get autoclean
RUN mkdir -p /etc/network
RUN touch /etc/network/interfaces

COPY id_rsa.pub /root/id_rsa.pub
RUN mkdir -p /root/.ssh
RUN cat /root/id_rsa.pub >> /root/.ssh/authorized_keys

