FROM alpine:latest
MAINTAINER Julien MANTEAU
LABEL Name=evpnlab-host Version=1.0.0
RUN apk update
RUN apk add sudo bash
RUN apk add nmap tshark tcpdump mtr iperf iperf3 htop bind-tools fping curl  
RUN apk add openssh
RUN rm -f /var/cache/apk/*
COPY .bashrc /root/.bashrc
